# tidal-sync: A high-performance tool for backing up and cloning Tidal libraries.
# Copyright (C) 2026 Leonid Dalin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, version 3 or later of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# Contact: infoLeonid@protonMail.com
class TidalSyncError(Exception):
    """
    Base exception for all tidal-sync errors.

    Catch this to handle any domain-specific error generated by the tool
    without accidentally suppressing standard library exceptions.
    """

    pass


class TidalAuthenticationError(TidalSyncError):
    """
    Raised when Tidal API authentication fails or returns an invalid user.

    Allows the CLI layer to exit gracefully rather than throwing a raw
    stack trace or relying on abrupt `SystemExit` calls.
    """

    pass


class TidalRateLimitError(TidalSyncError):
    """Raised when Tidal throttles us and the retry budget is exhausted."""

    pass


class TidalTransientError(TidalSyncError):
    """Raised when a retryable failure outlives the retry budget."""

    pass


class TidalPoisonError(TidalSyncError):
    """Raised when a specific item is rejected and must be dropped.

    Only a 403/404 (region lock or removed from catalogue) or an
    ObjectNotFound qualifies. Everything else is transient or fatal.
    """

    pass
